name: books
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  freezed: any
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.4
  dio: ^5.4.1
  dartz: ^0.10.1
  cached_network_image: ^3.3.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  provider: ^6.1.2


  cupertino_icons: ^1.0.6
  epub_view: ^3.2.0
  internet_file: ^1.2.0
  webview_flutter: ^2.0.14
  flutter_inappwebview: ^6.0.0
  oauth2: ^2.0.2
  flutter_rating_bar: ^4.0.1
  path_provider: ^2.0.2
  vocsy_epub_viewer: any
  permission_handler: ^11.3.0
  device_info_plus: ^9.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_file_downloader: ^1.2.1
  isar_generator: ^3.1.0+1





flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
